name: Auto Deploy Pipeline
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      CICD_GITHUB_TOKEN: ${{ secrets.CICD_GITHUB_TOKEN }}
      GCP_CICD_CLIENTS_PROD: ${{ vars.GCP_CICD_DEVOPS_CLIENTS_PROD }}      
      GCP_CICD_DEVOPS_CLIENTS_PROD: ${{ vars.GCP_CICD_DEVOPS_CLIENTS_PROD }} 
      GCP_CICD_CLIENTS_QA: ${{ vars.GCP_CICD_DEVOPS_CLIENTS_QA }}
      GCP_CICD_DEVOPS_CLIENTS_QA: ${{ vars.GCP_CICD_DEVOPS_CLIENTS_QA }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout Application Configuration
      uses: actions/checkout@v2  
      with:
        repository: londonhydro/GCP_Application_Configuration
        token: ${{ secrets.CICD_GITHUB_TOKEN }}
        repo-token: ${{ secrets.CICD_GITHUB_TOKEN }} 
        path: _config        
    - name: Checkout action tools
      uses: actions/checkout@v2  
      with:
        repository: londonhydro/github-actions-tools
        token: ${{ secrets.CICD_GITHUB_TOKEN }}
        repo-token: ${{ secrets.CICD_GITHUB_TOKEN }}
        path: _tools
    - name: Setup tools
      run: bash ./_tools/scripts/cicd_tools_setup.sh
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Code Sanitize
      run: ${TOOLS_PATH}/scripts/code_sanitize.sh
    - name: Setup Build Environment
      env:
        APP_SECRETS: ${{secrets.APP_SECRETS}}
        APP_SECRETS_ENV: ${{secrets.APP_SECRETS_ENV}}
      run: ${TOOLS_PATH}/scripts/build_setup.sh
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: ${{ env.GCP_VERSION}}
        service_account_key: ${{secrets[env.GOOGLE_APPLICATION_CREDENTIALS_KEY]}}
    - name: Build and Test
      run: ${TOOLS_PATH}/scripts/test.sh
    - name: Publish Result To DevOps MicroSite
      if: (success() || failure())
      run: ${TOOLS_PATH}/scripts/devops_site_publish.sh
    - name: Build for Deployment
      run: ${TOOLS_PATH}/scripts/build.sh
    - name: Setup for Deployment
      env:
        FIREBASE_TOKEN: ${{ secrets[env.FIREBASE_TOKEN_KEY] }}    
      run: ${TOOLS_PATH}/scripts/pre_deploy_setup.sh      
    - name: Build Docker Image
      run: ${TOOLS_PATH}/scripts/docker_build.sh
    - name: Deploy to Target Environment
      env:
        FIREBASE_TOKEN: ${{ secrets[env.FIREBASE_TOKEN_KEY] }}
      run: ${TOOLS_PATH}/scripts/deploy.sh
